services:
  sanitize-api:
    build:
      context: .
    container_name: sanitize-api
    ports:
      - "8080:8080"
    environment:
      OTEL_SDK_DISABLED: true
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"