services:
  sanitize-api:
    build: .
    container_name: sanitize-api
    ports:
      - "8081:8080"
    environment:
      OTEL_SDK_DISABLED: true
      SQL_USERNAME: "sa"
      SQL_PASSWORD: "YourStrong!Passw0rd"
    volumes:
      - ../../build/libs/app-0.0.1-SNAPSHOT.jar:/app/app.jar
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"