receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging:
    verbosity: detailed

  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers:  [ otlp ]
      processors: [ batch ]
      exporters:  [ logging, otlp/tempo ]
    logs:
      receivers:  [ otlp ]
      processors: [ batch ]
      exporters:  [ logging, loki ]
    metrics:
      receivers:  [ otlp ]
      processors: [ batch ]
      exporters:  [ logging ]