spring.application.name: flash-homework
springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  paths-to-match: /sanitize
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=santization_db;trustServerCertificate=true
    username: ${SQL_USERNAME:sa}
    password: ${SQL_PASSWORD:YourStrong!Passw0rd}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    url: jdbc:sqlserver://localhost:1433;databaseName=santization_db
    user: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.security: DEBUG
otel.exporter.otlp.endpoint: http://localhost:4318