spring.application.name: flash-homework
springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  paths-to-match: /sanitize
#server:
#  ssl:
#    trust-store: classpath:ssl/custom-truststore.jks
#    trust-store-password: changeit
#    key-store: classpath:ssl/my-keystore.jks
#    key-alias: keystore
#    key-store-password: changeit
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=santization_db;trustServerCertificate=true #;encrypt=true;integratedSecurity=true;trustServerCertificate=true;
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
#    https://stackoverflow.com/a/63773348/17164601 - authenticationScheme=NTLM
    url: jdbc:sqlserver://localhost:1433;databaseName=santization_db #;authenticationScheme=NTLM;trustServerCertificate=true #;encrypt=true;integratedSecurity=true;trustServerCertificate=true;
    user: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.security: DEBUG
otel:
  exporter:
    otlp:
        endpoint: http://localhost:4318