spring.application.name: flash-homework
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  paths-to-exclude: /internal
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=santization_db;encrypt=false # TODO: encrypt=true & setup server cert
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
logging:
  level:
    org.flywaydb: DEBUG